/**
 * FoodSave - Realistic Sample Data
 * Tailored for college campus, canteen, hostel, and local food rescue demonstration.
 */

const SAMPLE_DONATIONS = [
  {
    id: "don-1",
    title: "Steamed Basmati Rice, Paneer Curry & Dal Fry",
    description: "Freshly prepared lunch buffet surplus from university noon rush. Cooked in hygienic campus central kitchen with filtered water and quality ingredients.",
    food_type: "cooked_meals",
    quantity_meals: 35,
    quantity_weight_kg: 14.0,
    provider_name: "Central Campus Dining Hall",
    provider_type: "college_canteen",
    pickup_address: "Campus North Block, 2nd Floor Dining Court, Service Door B",
    pickup_instructions: "Ring kitchen bell at Service Door B. Thermal food-grade containers can be transferred into your vessels or returned tomorrow morning.",
    available_until: new Date(Date.now() + 3.5 * 60 * 60 * 1000).toISOString(),
    status: "available",
    dietary_type: "vegetarian",
    storage_notes: "Held in commercial electric warming cabinets at 68°C. Safe, hot and ready to serve immediately.",
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
    contact_phone: "+1 (555) 234-5678",
    contact_name: "Chef Rajesh Kumar",
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "don-2",
    title: "Artisan Sourdough, Baguettes & Butter Croissants",
    description: "Day-bake fresh artisan sourdough loaves, seeded baguettes, flaky croissants, and blueberry pastries. Crisp crusts and baked this morning.",
    food_type: "bakery",
    quantity_meals: 40,
    quantity_weight_kg: 12.5,
    provider_name: "Golden Crust Bakery & Cafe",
    provider_type: "restaurant",
    pickup_address: "42 University Avenue, Downtown (Opposite North Gate)",
    pickup_instructions: "Enter through front cafe counter and mention FoodSave claim to the barista on duty.",
    available_until: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    status: "available",
    dietary_type: "vegetarian",
    storage_notes: "Individually packed in clean dry bakery paper bags. Keep dry and at room temperature.",
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    contact_phone: "+1 (555) 345-6789",
    contact_name: "Elena Rostova",
    created_at: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
  },
  {
    id: "don-3",
    title: "Mixed Herb Penne Pasta & Foil Garlic Toasts",
    description: "Creamy roasted garlic and tomato herb penne pasta tossed with fresh broccoli florets, zucchini, bell peppers, and individually wrapped garlic toasts.",
    food_type: "cooked_meals",
    quantity_meals: 18,
    quantity_weight_kg: 7.2,
    provider_name: "Oakridge Hostel Mess (Wing B)",
    provider_type: "hostel_mess",
    pickup_address: "Student Hostel Zone 4, Mess Kitchen Loading Dock",
    pickup_instructions: "Security gate has guest logbook. Tell guard you are picking up FoodSave mess package.",
    available_until: new Date(Date.now() + 2.25 * 60 * 60 * 1000).toISOString(),
    status: "available",
    dietary_type: "vegetarian",
    storage_notes: "Insulated catering trays with foil lids. Keep warm.",
    image_url: "https://images.unsplash.com/photo-1621996346565-e3d5d6281691?auto=format&fit=crop&w=800&q=80",
    contact_phone: "+1 (555) 456-7890",
    contact_name: "Vikram Patel",
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "don-4",
    title: "Gourmet Wrap Platters & Seasonal Fruit Cups",
    description: "Catering surplus from Annual Tech Summit banquet: Mediterranean falafel wraps, avocado grilled veggie rolls, and chilled watermelon-berry cups.",
    food_type: "cooked_meals",
    quantity_meals: 28,
    quantity_weight_kg: 11.0,
    provider_name: "Annual Tech Summit Catering",
    provider_type: "event_catering",
    pickup_address: "Student Convention Center, Hall 3 Backstage Service Ramp",
    pickup_instructions: "Call coordinator Maria on arrival; security will open loading bay gate.",
    available_until: new Date(Date.now() + 1.75 * 60 * 60 * 1000).toISOString(),
    status: "claimed",
    dietary_type: "vegan",
    storage_notes: "Chilled in commercial food cooler with dry cold packs (4°C).",
    image_url: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    contact_phone: "+1 (555) 567-8901",
    contact_name: "Maria Santos",
    created_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    claim_id: "clm-1",
    receiver_name: "Marcus Chen",
    receiver_organization: "Campus Food Rescue Network",
    receiver_phone: "+1 (555) 987-6543",
    claim_code: "FS-7491",
    estimated_pickup_time: "In 30 minutes (van pickup)",
    claimed_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: "don-5",
    title: "Crisp Red Apples, Bananas & Citrus Fruit Crates",
    description: "Fresh surplus fruit boxes harvest from student agricultural cooperative. Unblemished, sweet, vitamin-rich and perfect for students or community kitchens.",
    food_type: "fresh_produce",
    quantity_meals: 50,
    quantity_weight_kg: 22.0,
    provider_name: "Green Roots Campus Co-op",
    provider_type: "college_canteen",
    pickup_address: "Agricultural Sciences Greenhouse B, Entry Bay 1",
    pickup_instructions: "Sturdy wooden crates available with handles. Trolley available on site to wheel to car.",
    available_until: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    status: "available",
    dietary_type: "vegan",
    storage_notes: "Stored at shaded room temperature (18°C). Excellent shelf life.",
    image_url: "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=800&q=80",
    contact_phone: "+1 (555) 678-9012",
    contact_name: "Samira Vance",
    created_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
  },
  {
    id: "don-6",
    title: "Gourmet Roasted Herb Medley & Creamy Potato Puree",
    description: "Faculty dinner banquet surplus: Rosemary infused roasted autumn vegetables, creamy whipped garlic potatoes, and mushroom herb reduction.",
    food_type: "cooked_meals",
    quantity_meals: 30,
    quantity_weight_kg: 13.5,
    provider_name: "University Faculty Club",
    provider_type: "restaurant",
    pickup_address: "Alumni Hall, West Wing Service Entrance",
    pickup_instructions: "Pickup directly at chef's office behind main kitchen.",
    available_until: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    status: "picked_up",
    dietary_type: "vegetarian",
    storage_notes: "Insulated hot transport boxes.",
    image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80",
    contact_phone: "+1 (555) 789-0123",
    contact_name: "Chef Antoine",
    created_at: new Date(Date.now() - 360 * 60 * 1000).toISOString(),
    claim_id: "clm-2",
    receiver_name: "Sarah Jenkins",
    receiver_organization: "Hope Community Shelter",
    receiver_phone: "+1 (555) 444-2222",
    claim_code: "FS-3189",
    estimated_pickup_time: "Completed",
    claimed_at: new Date(Date.now() - 300 * 60 * 1000).toISOString(),
    picked_up_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
  },
  {
    id: "don-7",
    title: "Organic Whole Milk, Greek Yogurts & Oat Drinks",
    description: "Commercial chilled dairy cases with 4 days before date stamp. Sealed packages including 12 liters organic milk, 20 Greek yogurt tubs, and 8 oat milk cartons.",
    food_type: "dairy_beverages",
    quantity_meals: 24,
    quantity_weight_kg: 15.0,
    provider_name: "West Campus Grocers & Cafe",
    provider_type: "supermarket",
    pickup_address: "Campus Commercial Plaza, Suite 108",
    pickup_instructions: "Ask for manager Liam at customer service desk.",
    available_until: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    status: "available",
    dietary_type: "vegetarian",
    storage_notes: "Maintained in reach-in commercial dairy cooler at 3.2°C.",
    image_url: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80",
    contact_phone: "+1 (555) 890-1234",
    contact_name: "Liam Thorne",
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  }
];

const PRESET_DONATIONS_FOR_DEMO = [
  {
    title: "Fresh Biryani & Spiced Raita Trays",
    description: "Rich fragrant basmati rice with golden potatoes, cauliflower, and cardamom, accompanied by cucumber yogurt raita.",
    food_type: "cooked_meals",
    quantity_meals: 25,
    quantity_weight_kg: 10.0,
    provider_name: "Central Campus Dining Hall",
    provider_type: "college_canteen",
    pickup_address: "Campus North Block, 2nd Floor Kitchen Entrance",
    pickup_instructions: "Ring kitchen doorbell; ask for Chef Rajesh.",
    dietary_type: "vegetarian",
    storage_notes: "Thermal hot boxes (65°C)",
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    contact_name: "Chef Rajesh Kumar",
    contact_phone: "+1 (555) 234-5678",
  },
  {
    title: "Sandwich Assortment & Fresh Bagels",
    description: "Assorted deli rolls, egg-mayo bagels, cheese tomato panini, wrapped in recyclable parchment.",
    food_type: "bakery",
    quantity_meals: 30,
    quantity_weight_kg: 8.5,
    provider_name: "Library Corner Cafe",
    provider_type: "restaurant",
    pickup_address: "Main Library Ground Floor, East Patio Door",
    pickup_instructions: "Pickup directly at side service door.",
    dietary_type: "vegetarian",
    storage_notes: "Refrigerated bakery display case (4°C)",
    image_url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    contact_name: "Hannah Lee",
    contact_phone: "+1 (555) 777-9911",
  },
  {
    title: "Surplus Fresh Garden Salad Bowls",
    description: "Crisp romaine, cherry tomatoes, cucumbers, shredded carrots with individual olive oil and lemon dressings.",
    food_type: "fresh_produce",
    quantity_meals: 20,
    quantity_weight_kg: 6.0,
    provider_name: "Engineering Green Bistro",
    provider_type: "college_canteen",
    pickup_address: "Engineering Quad, Building 4 Atrium",
    pickup_instructions: "Available until 6 PM at bistro counter.",
    dietary_type: "vegan",
    storage_notes: "Chilled salad cooler",
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    contact_name: "David Kim",
    contact_phone: "+1 (555) 321-4321",
  }
];

// Export for browser script usage
if (typeof window !== "undefined") {
  window.FoodSaveMockData = {
    SAMPLE_DONATIONS,
    PRESET_DONATIONS_FOR_DEMO,
  };
}
